#!/bin/bash
# install.sh — Set up session-continuity for your environment

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== Session Continuity Setup ==="
echo ""

# 1. Projects directory
read -rp "Path to your projects directory [$HOME/Projects]: " input_dir
PROJECTS_DIR="${input_dir:-$HOME/Projects}"

if [ ! -d "$PROJECTS_DIR" ]; then
    echo "WARNING: Directory does not exist: $PROJECTS_DIR"
    read -rp "Create it? [y/N]: " create_dir
    if [[ "$create_dir" =~ ^[Yy] ]]; then
        mkdir -p "$PROJECTS_DIR"
        echo "Created: $PROJECTS_DIR"
    fi
fi

# 2. Skip dirs
read -rp "Directories to skip (space-separated, or leave empty): " SKIP_DIRS

# 3. Write config
cat > "$SCRIPT_DIR/config" << EOF
# session-continuity configuration (generated by install.sh)
PROJECTS_DIR="$PROJECTS_DIR"
SKIP_DIRS="$SKIP_DIRS"
ACTIVITY_WINDOW=30
EOF

echo ""
echo "Config written to: $SCRIPT_DIR/config"

# 4. Ensure scripts are executable
chmod +x "$SCRIPT_DIR/auto-save-sessions.sh"
chmod +x "$SCRIPT_DIR/save-session.sh"

# 5. Cron setup
echo ""
read -rp "Install cron job (runs every 10 minutes)? [Y/n]: " install_cron
if [[ ! "$install_cron" =~ ^[Nn] ]]; then
    CRON_CMD="*/10 * * * * $SCRIPT_DIR/auto-save-sessions.sh >> $SCRIPT_DIR/session-autosave.log 2>&1"
    if crontab -l 2>/dev/null | grep -qF "auto-save-sessions.sh"; then
        echo "Cron entry already exists. Skipping."
    else
        (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
        echo "Cron job installed."
    fi
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Projects dir: $PROJECTS_DIR"
echo "Config file:  $SCRIPT_DIR/config"
echo ""
echo "Next steps:"
echo "  1. Copy the content from templates/CLAUDE_MD_SNIPPET.md into each project's CLAUDE.md"
echo "  2. Run ./save-session.sh [project-name] to initialize a project"
echo "  3. To resume a session, tell Claude:"
echo "     Read /path/to/project/CLAUDE.md and /path/to/project/SESSION_STATE.md and pick up where I left off."
echo ""
